# Generated by Django 4.2.3 on 2023-07-08 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinamicform',
            name='option',
        ),
        migrations.AddField(
            model_name='dinamicform',
            name='option_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dinamyc.optiona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinamicform',
            name='option_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dinamyc.optionb'),
            preserve_default=False,
        ),
    ]
