# Generated by Django 4.2.3 on 2023-07-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_inventario', '0002_movimientoinventario_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('umed', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('costo_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='almacen_afectado',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='almacen_destino',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='documento',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='nit',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='nota_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='nota_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='nota_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='orden_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='sucursal',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('T', 'Traslado'), ('P', 'Proveedores')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='transporte',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MovimientoInventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movimiento_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento_inventario.movimientoinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento_inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='prodcutos',
            field=models.ManyToManyField(through='movimiento_inventario.MovimientoInventarioProducto', to='movimiento_inventario.producto'),
        ),
    ]
