# Generated by Django 4.2.3 on 2023-07-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_inventario', '0004_rename_total_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventarioproducto',
            name='descripcion',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventarioproducto',
            name='umed',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
