# Generated by Django 4.2.3 on 2023-07-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_inventario', '0005_movimientoinventarioproducto_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='almacen_destino',
        ),
        migrations.AlterField(
            model_name='movimientoinventarioproducto',
            name='umed',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='almacen_afectado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacen_afectado', to='movimiento_inventario.almacen'),
        ),
    ]
