# Generated by Django 4.2.3 on 2023-07-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_inventario', '0006_almacen_remove_movimientoinventario_almacen_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='almacen_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='almacen_destino', to='movimiento_inventario.almacen'),
            preserve_default=False,
        ),
    ]
