# Generated by Django 4.2.3 on 2023-07-08 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_inventario', '0008_rename_prodcutos_movimientoinventario_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMoinventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha', 'documento'], 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterField(
            model_name='movimientoinventarioproducto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento_inventario.tipomoinventario'),
        ),
    ]
